In [1]:
print(1e7)

10000000.0


In [2]:
print(1e-3)

0.001


In [3]:
print("Hello world")
print("What")

Hello world
What


In [4]:
temp =""" Hello {}, Good morning I thought i had to give you a morning {}, which is very essential for your daily routine, and if you sometimes want {}, then just ask for it."""


In [5]:
output_str = temp.format("Anup","Blowjob","My Pussy")

In [6]:
kanto = [73,67,43]
weights = [0.3,0.2,0.5]
result = 0.0
for r,w in zip(kanto,weights):
    result += r*w
    
print(result)

56.8


In [7]:
import numpy as np


In [8]:
kanto = np.array(kanto)
weights = np.array(weights)




In [9]:
regions = np.array([
    [12,13,14],
    [18,17,16],
    [21,23,27],
    [31,22,15],
    [25,19,31]
])
regions

array([[12, 13, 14],
       [18, 17, 16],
       [21, 23, 27],
       [31, 22, 15],
       [25, 19, 31]])

In [10]:
regions.shape


(5, 3)

In [11]:
yeilds = regions @ weights
yeilds = yeilds.reshape(5,1)
yeilds

array([[13.2],
       [16.8],
       [24.4],
       [21.2],
       [26.8]])

In [12]:
result = np.concatenate((regions,yeilds),axis=1)
result

array([[12. , 13. , 14. , 13.2],
       [18. , 17. , 16. , 16.8],
       [21. , 23. , 27. , 24.4],
       [31. , 22. , 15. , 21.2],
       [25. , 19. , 31. , 26.8]])

In [13]:
np.savetxt('yield.txt',result,fmt='%.2f',comments = '',header = 'temperature,rainfall,humidity,yield_apples')

In [14]:
arr1 = np.array([[[11.0,12.0,13.0,14.0,15.0],
                  [13.0,14.0,15.0,19.0,16.0]],
                 
                 [[21.0,22.0,23.0,24.0,25.0],
                  [23.0,27.0,19.0,29.0,24.0]],

                 [[31.0,32.0,33.0,34.0,35.0],
                  [33.0,34.0,28.0,23.0,11.0]]
                
                ])
arr1

array([[[11., 12., 13., 14., 15.],
        [13., 14., 15., 19., 16.]],

       [[21., 22., 23., 24., 25.],
        [23., 27., 19., 29., 24.]],

       [[31., 32., 33., 34., 35.],
        [33., 34., 28., 23., 11.]]])

In [15]:
#Problem1
arr1[1,1,2]

np.float64(19.0)

In [16]:
#Solution1
arr1[1]

array([[21., 22., 23., 24., 25.],
       [23., 27., 19., 29., 24.]])

In [17]:
arr1[1,1]

array([23., 27., 19., 29., 24.])

In [18]:
arr1[1,1,2]

np.float64(19.0)

In [19]:
#Problem2
arr1[1:,0:1,:2]

array([[[21., 22.]],

       [[31., 32.]]])

In [20]:
#Solution2
arr1[1:]

array([[[21., 22., 23., 24., 25.],
        [23., 27., 19., 29., 24.]],

       [[31., 32., 33., 34., 35.],
        [33., 34., 28., 23., 11.]]])

In [21]:
arr1[1:,0:1]

array([[[21., 22., 23., 24., 25.]],

       [[31., 32., 33., 34., 35.]]])

In [22]:
arr1[1:,0:1,:2]

array([[[21., 22.]],

       [[31., 32.]]])

In [23]:
#some func in numpy
arr2 = np.arange(11,90,3)
arr2

array([11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59,
       62, 65, 68, 71, 74, 77, 80, 83, 86, 89])

In [24]:
arr2.shape

(27,)

In [25]:
arr2.reshape(3,3,3)

array([[[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]],

       [[38, 41, 44],
        [47, 50, 53],
        [56, 59, 62]],

       [[65, 68, 71],
        [74, 77, 80],
        [83, 86, 89]]])

In [26]:
arr2.reshape(27,1)

array([[11],
       [14],
       [17],
       [20],
       [23],
       [26],
       [29],
       [32],
       [35],
       [38],
       [41],
       [44],
       [47],
       [50],
       [53],
       [56],
       [59],
       [62],
       [65],
       [68],
       [71],
       [74],
       [77],
       [80],
       [83],
       [86],
       [89]])

In [27]:
import os

In [28]:
os.getcwd()

'/storage/emulated/0/My Documents/PYTHON'

In [29]:
os.listdir()

['PROJECT BLACKJACK.py',
 'Guess The Number.py',
 'Number Guessing Game.py',
 'maths.py',
 'OOP Practice.py',
 'IMPROVED Calculator.py',
 'DateTime.py',
 'Numpy 1.py',
 'Numpy 2.py',
 'Numpy 3.py',
 'QrcodeGen.py',
 'Use of lambda and one liner for.py',
 'OOP.py',
 'GCD Function.py',
 'mfi261C.tmp',
 'Photo.jpg',
 'Mechanics Excel Generator.py',
 'Mechanics_Problem.xlsx',
 'mfi65D8.tmp',
 'web Scraper.py',
 'Untitled.ipynb',
 '.ipynb_checkpoints',
 'yield.txt',
 'data']

In [30]:
file1 = open('./yield.txt','r')
file1_content = file1.read()
print(file1_content)
file1.close()

temperature,rainfall,humidity,yield_apples
12.00 13.00 14.00 13.20
18.00 17.00 16.00 16.80
21.00 23.00 27.00 24.40
31.00 22.00 15.00 21.20
25.00 19.00 31.00 26.80



In [31]:
os.makedirs('./data',exist_ok=True)

In [32]:
os.listdir()

['PROJECT BLACKJACK.py',
 'Guess The Number.py',
 'Number Guessing Game.py',
 'maths.py',
 'OOP Practice.py',
 'IMPROVED Calculator.py',
 'DateTime.py',
 'Numpy 1.py',
 'Numpy 2.py',
 'Numpy 3.py',
 'QrcodeGen.py',
 'Use of lambda and one liner for.py',
 'OOP.py',
 'GCD Function.py',
 'mfi261C.tmp',
 'Photo.jpg',
 'Mechanics Excel Generator.py',
 'Mechanics_Problem.xlsx',
 'mfi65D8.tmp',
 'web Scraper.py',
 'Untitled.ipynb',
 '.ipynb_checkpoints',
 'yield.txt',
 'data']

In [33]:
os.listdir('./data')

['italy-covid-daywise.csv']

In [34]:
url1 = "https://hub.jovian.ml/wp-content/uploads/2020/08/loans1.txt"


In [35]:
import urllib.request

In [38]:
#Pandas

In [1]:
import pandas as pd

In [2]:
covid_df = pd.read_csv('./data/italy-covid-daywise.csv')

In [3]:
covid_df

,date,new_cases,new_deaths,new_tests
0,2019-12-31,0.0,0.0,NaN
1,2020-01-01,0.0,0.0,NaN
2,2020-01-02,0.0,0.0,NaN
3,2020-01-03,0.0,0.0,NaN
4,2020-01-04,0.0,0.0,NaN
...,...,...,...,...
243,2020-08-30,1444.0,1.0,53541.0
244,2020-08-31,1365.0,4.0,42583.0
245,2020-09-01,996.0,6.0,54395.0
246,2020-09-02,975.0,8.0,NaN


In [4]:
type(covid_df)

pandas.core.frame.DataFrame

In [5]:
covid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   date        248 non-null    object 
 1   new_cases   248 non-null    float64
 2   new_deaths  248 non-null    float64
 3   new_tests   135 non-null    float64
dtypes: float64(3), object(1)
memory usage: 7.9+ KB


In [6]:
covid_df.describe()

,new_cases,new_deaths,new_tests
count,248.000000,248.000000,135.000000
mean,1094.818548,143.133065,31699.674074
std,1554.508002,227.105538,11622.209757
min,-148.000000,-31.000000,7841.000000
25%,123.000000,3.000000,25259.000000
50%,342.000000,17.000000,29545.000000
75%,1371.750000,175.250000,37711.000000
max,6557.000000,971.000000,95273.000000


In [10]:
covid_df.columns

Index(['date', 'new_cases', 'new_deaths', 'new_tests'], dtype='object')

In [11]:
covid_df.shape

(248, 4)